### ISSUE TITLE
Issue during investigation

### ISSUE THREAD

**Issue by cooktheryan** [projectatomic/commissaire#141]
I'm trying to join hosts to a new cluster but hitting 

(commissaire)[root@ip-10-20-1-224 cloud-init]# 2016-06-10 11:55:52,291 - investigator - 26702 -  140680834725696 - INFO - 52.91.42.114 is now in investigating.
2016-06-10 11:55:52,292 - investigator - 26702 -  140680834725696 - INFO - Wrote key for 52.91.42.114
2016-06-10 11:55:52,304 - investigator - 26702 -  140680834725696 - WARNING - Getting info failed for 52.91.42.114: 'NoneType' object has no attribute 'terminate'

Using master branch.

**Comment by cooktheryan** [comment]
@mbarnes any help you can provide would be appreciated

**Comment by mbarnes** [comment]
I'm familiar with the error message from recent changes, but I thought we managed to work around it.  Perhaps not... I'll investigate further.

Is this actually preventing new hosts from joining a cluster, or is it just a nuisance warning in the log?

**Comment by cooktheryan** [comment]
Currently no hosts will join the cluster as its failing during the initial investigation

**Comment by cooktheryan** [comment]
Interesting. The hosts appear when running commctl host list but I dont believe it runs through the process of starting and configuring services

**Comment by mbarnes** [comment]
That part makes sense.  The initial investigation runs after the host is added internally.

**Comment by mbarnes** [comment]
Got a backtrace on the warning and found it's coming from Ansible's `Process` object.  I managed to work around the issue for our own `Process` objects, but this one's out of my reach.  Need to figure out why that's happening in the first place.
```
2016-06-10 16:11:45,122 - investigator - 3375 -  140484503799552 - WARNING - Getting info failed for 10.2.0.2: 'NoneType' object has no attribute 'terminate'
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/commissaire/jobs/investigator.py", line 103, in investigator
    result, facts = transport.get_info(address, key_file)
  File "build/bdist.linux-x86_64/egg/commissaire/transport/ansibleapi.py", line 304, in get_info
    result, fact_cache = self._run(ip, key_file, play_file)
  File "build/bdist.linux-x86_64/egg/commissaire/transport/ansibleapi.py", line 219, in _run
    tqm.cleanup()
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/ansible-2.0.1.0-py2.7.egg/ansible/executor/task_queue_manager.py", line 246, in cleanup
    self._cleanup_processes()
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/ansible-2.0.1.0-py2.7.egg/ansible/executor/task_queue_manager.py", line 250, in _cleanup_processes
    self._result_prc.terminate()
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/ansible-2.0.1.0-py2.7.egg/ansible/executor/process/result.py", line 89, in terminate
    super(ResultProcess, self).terminate()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 137, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by ashcrow** [comment]
@mbarnes don't forget to let @cooktheryan know when you think this is ready to be validated.

**Comment by mbarnes** [comment]
@cooktheryan Can you try this again?

https://github.com/projectatomic/commissaire/pull/143 may have fixed the immediate problem but I'm still working on a better long-term solution.

**Comment by cooktheryan** [comment]
This merge/fix works! Woot good work @mbarnes

**Comment by ashcrow** [comment]
:+1: for @mbarnes :smile:

**Comment by mbarnes** [comment]
Cool!  Closing this then and hoping I don't cause any more regressions.  :cold_sweat:
