### ISSUE TITLE
Uncaught KubernetesStoreHandler exception

### ISSUE THREAD

**Issue by mbarnes** [projectatomic/commissaire#177]
Encountered this while futzing around trying to get the new Kubernetes integration working.

It was ultimately due to a misconfiguration on my part but still, we should be catching and handling this exception and any others that store handlers might throw.
```
Traceback (most recent call last):
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
    req.respond()
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
    self.server.gateway(self).respond()
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/wsgiserver/wsgiserver2.py", line 2115, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cptree.py", line 290, in __call__
    return app(environ, start_response)
  File "/home/mbarnes/commissaire/lib/python2.7/site-packages/falcon/api.py", line 189, in __call__
    responder(req, resp, **params)
  File "build/bdist.linux-x86_64/egg/commissaire/handlers/hosts.py", line 153, in on_put
    address, ssh_priv_key, remote_user, cluster_name)
  File "build/bdist.linux-x86_64/egg/commissaire/handlers/util.py", line 237, in etcd_host_create
    new_host = store_manager.save(host)
  File "build/bdist.linux-x86_64/egg/commissaire/store/storehandlermanager.py", line 165, in save
    model_instance = handler._save(model_instance)
  File "build/bdist.linux-x86_64/egg/commissaire/store/kubestorehandler.py", line 262, in _save
    return self._dispatch('save', model_instance)
  File "build/bdist.linux-x86_64/egg/commissaire/store/kubestorehandler.py", line 251, in _dispatch
    return func(model_instance)
  File "build/bdist.linux-x86_64/egg/commissaire/store/kubestorehandler.py", line 312, in _save_host
    return self._format_model(response.json(), model_instance)
  File "build/bdist.linux-x86_64/egg/commissaire/store/kubestorehandler.py", line 150, in _format_model
    model_instance.primary_key))
KeyError: 'No annotations for 192.168.122.229'
```

**Comment by ashcrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gGXh5sRN&#x2F;384-1-multi-host-mgr-bug-uncaught-kubernetesstorehandler-exception"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (1) [multi-host-mgr] [bug] Uncaught KubernetesStoreHandler exception</a>

**Comment by mbarnes** [comment]
> It was ultimately due to a misconfiguration on my part but still, we should be catching and handling this exception and any others that store handlers might throw.

Actually no, it's a legit bug.  The store handler expects to find metadata for a host record that hasn't been added yet.

**Comment by mbarnes** [comment]
@ashcrow  It looks to me the problem is all the "save" methods in `KubernetesStoreHandler` use `PATCH`, where I believe `POST` is needed for this particular case.

This makes me wonder if we should split the `save()` method into distinct `create()` and `update()` methods so one can use `POST` and the other `PATCH` if needed (`EtcdStoreHandler` wouldn't need to distinguish).  I *think* all the call points in the HTTP handler code should know which method they need.

**Comment by ashcrow** [comment]
That makes sense to me. I'll code this up today.

**Comment by ashcrow** [comment]
I see you already snagged the card. I'll let you run with it.

**Comment by mbarnes** [comment]
Abandoning my initial idea.  The real problem is Commissaire needs to wait until bootstrapping is finished before attempting to patch the Kubernetes annotations, otherwise there's nothing yet there to patch.
